site_name: Cosmologist To Technologist
nav:
  - Home: index.md
  # - cosmology.md
  # - Computing:
  #     - docker.md
  #     - python.md
  #     - r.md
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
  font:
    texr: Roboto Mono
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bkmarzouk/
    - icon: fontawesome/brands/github
      link: https://www.github.com/bkmarzouk/